<?php
/**
 * Created by PhpStorm.
 * User: abdujabbor
 * Date: 8/8/18
 * Time: 1:50 PM
 */

namespace abdujabbor\counter;

use abdujabbor\counter\io\IOStream;

class LinkClickCounter extends AbstractEventCounter
{
    protected $requiredFields = ['id', 'link'];
    public function __construct(IOStream $io, array $args = [])
    {
        parent::__construct($io, $args);
        $this->setEvent(EventTypes::EVENT_CLICK);
    }

    public function generateKey(): string
    {
        return (string) $this->args['link'];
    }

    public function generateRecord(): array
    {
        // TODO: Implement generateRecord() method.
    }

    public function getAmount(): int
    {
        // TODO: Implement getAmount() method.
    }

    public function incrementAmount(): void
    {
        // TODO: Implement incrementAmount() method.
    }

    public function availableForIncrement(): bool
    {
        // TODO: Implement availableForIncrement() method.
    }


    public function validateInputParams(): bool
    {
        return parent::validateInputParams(); // TODO: Change the autogenerated stub
    }
}
