<?php
/**
 * Created by PhpStorm.
 * User: abdujabbor
 * Date: 8/8/18
 * Time: 1:50 PM
 */

namespace abdujabbor\counter;

class LinkClickEvent extends AbstractEventCounter
{
    protected $requiredFields = ['id', 'link'];

    /**
     * LinkClickEvent constructor.
     * @param int $amount
     * @param array $args
     */
    public function __construct(int $amount = 0, array $args = [])
    {
        parent::__construct($amount, $args);
        $this->setEvent(EventTypes::EVENT_CLICK);
    }

    /**
     * @return string
     */
    public function generateKey(): string
    {
        return (string) $this->args['link'];
    }

    /**
     * @return array
     */
    public function generateRecord(): array
    {
        // TODO: Implement generateRecord() method.
    }

    /**
     * @return int
     */
    public function getAmount(): int
    {
        // TODO: Implement getAmount() method.
    }

    /**
     * @void
     */
    public function incrementAmount(): void
    {
        // TODO: Implement incrementAmount() method.
    }

    /**
     * @return bool
     */
    public function availableForIncrement(): bool
    {
        // TODO: Implement availableForIncrement() method.
    }

    /**
     * @return bool
     */
    protected function validateInputParams(): bool
    {
        return parent::validateInputParams(); // TODO: Change the autogenerated stub
    }
}
