<?php
/**
 * Created by PhpStorm.
 * User: abdujabbor
 * Date: 8/8/18
 * Time: 12:26 PM
 */

namespace abdujabbor\counter;

use abdujabbor\counter\io\IOStream;

class PostViewCounter extends AbstractEventCounter
{
    protected $requiredFields = ['id'];

    /**
     * PostViewCounter constructor.
     * @param IOStream $io
     * @param array $args
     */
    public function __construct(IOStream $io, array $args = [])
    {
        parent::__construct($io, $args);
        $this->setEvent(EventTypes::EVENT_VIEW);
    }

    /**
     * @return string
     */
    public function generateKey(): string
    {
        $this->key = (string) $this->args['id'];
        return $this->key;
    }

    /**
     * @return array
     */
    public function generateRecord(): array
    {
        $browser = get_browser();
        return [
            'id' => $this->key,
            'event' => $this->event,
            'ip' => $_SERVER['REMOTE_ADDR'],
            'browser' => $browser['browser'],
            'platform' => $browser['platform'],
            'version' => $browser['version'],
            'time' => time(),
        ];
    }

    /**
     * @return int
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * @return bool
     */
    public function availableForIncrement(): bool
    {
        return true;
    }

    /**
     * @return bool
     */
    public function validateInputParams(): bool
    {
        return parent::validateInputParams(); // TODO: Change the autogenerated stub
    }
}
